# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    desc: List all tasks
    silent: true
    cmds:
      - echo $'To list all tasks run:\n\n\t task --list-all\n'
      - task --list --sort=none

  setup:
    desc: Install required global Go dependencies
    cmds:
      - mise install

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  lint:fix:
    desc: Run Go lint and fix
    cmds:
      - golangci-lint run --fix

  test:
    desc: Run tests
    deps: [lint]
    cmds:
      - gotestsum

  test:update-snapshots:
    desc: Run tests
    deps: [lint]
    env:
      UPDATE_SNAPSHOTS: true
    cmds:
      - gotestsum

  test:update-fixtures:
    desc: Remove vcr fixtures and rerecord them
    deps: [lint]
    cmds:
      - echo "Finding and removing VCR fixture directories..."
      - fd "fixtures" --type directory | xargs rm -rf
      - gotestsum

  run:
    desc: Run the app
    cmds:
      - go run main.go

  build:
    desc: Build binary
    cmds:
      - go build -o bin/tamjaweb
