name: Go CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up mise
        uses: jdx/mise-action@v2
        with:
          cache: true

      - name: Set up Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Install dependencies
        run: task setup

      - name: Lint
        run: task lint

      - name: Test
        run: task test

      - name: Build
        run: task build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tamjaweb
          path: bin/tamjaweb
